### ISSUE TITLE
documentation for submitters

### ISSUE THREAD

**Issue by benchoufi** [echopen/PRJ-medtec_androidapp#3]
We can start writing documentations about the project, its components, its milestones and the rules & formats of code to respect for any new submitter @yaf @kelu124

**Comment by kelu124** [comment]
Started: on boucle? :)

**Comment by benchoufi** [comment]
yes right ;)

**Comment by loic-fejoz** [comment]
Usually there is a link in the bug tracker to the resolution... Where are the rules? Any pointer?

**Comment by benchoufi** [comment]
the bug tracker is on GitHub. We are defining some specific paths to document echopen's workflows. What would be natural is to document on Github's wiki the soft part. We can begin a contribution guide there. 

@kelu124 suggest to summerize the github's wiki content on [echopen](echopen.org) wiki.

**Comment by loic-fejoz** [comment]
@benchoufi Maybe I haven't read enough the wiki, but could you provide me with pointer (url) to
- the components of the project?
- the milestone? http://echopen.org/index.php?title=Planning
- the rules & formats of code to respect?

Thanks

**Comment by benchoufi** [comment]
we're having a camp this week-end, working on the projects's component. We'll bring a fresh clear documentation just after. Btw, sorry I was not clear, the rules, format's and more broadly the contributing guide need to be set. We will do that on the echopen's wiki !

**Comment by yaf** [comment]
We need to change name... Project is a no-name-project ... :-)

**Comment by kelu124** [comment]
There's a brand new page : http://echopen.org/index.php?title=How_to_Contribute =)
