### ISSUE TITLE
Formation GitHub

### ISSUE THREAD

**Issue by ghost** [echopen/PRJ-medtec_androidapp#4]
Merci Mehdi de faire une formation GitHub <3

**Comment by yaf** [comment]
Si vous avez besoin d'aide sur github ET git, je peux aussi vous organiser ça si vous voulez :-p

**Comment by benchoufi** [comment]
yes c le bienvenu, sachant que les formations couplent déjà git et github. 

ca se passe le vendredi 14h/16h - mais ce n'est pas suffisant - quelles sont tes dispo

**Comment by yaf** [comment]
Pas nombreuses en ce moment... Quel est le besoin ? Vous avez essayé try git ? https://try.github.io

**Comment by benchoufi** [comment]
déjà pour try git

besoin : formation au ligne de commande + git
tps : 1 à 2h/semaine

**Comment by yaf** [comment]
http://git-scm.com/book/en/v2 un bon bouquin (gratuit) sur git

**Comment by benchoufi** [comment]
yep c une bonne ressource - j'aimerais qu'ils le découvrent seuls - ils
n'ont pas encore le réflexe de chercher des tuto...

Le jeu. 27 août 2015 à 17:06, Yannick François notifications@github.com a
écrit :

**Comment by yaf** [comment]
Ils sont là pour apprendre le code où pour travailler sur la sonde ? :-D
