### ISSUE TITLE
data file to scan convert

### ISSUE THREAD

**Issue by benchoufi** [echopen/PRJ-medtec_androidapp#5]
@loic-fejoz 
the phantom rep is not clear -> the data file `img_kydney.txt` is the raw signal that needs to be filtered. It is the resource for the envelope detection from which pixels intensity are deduced. The resulting pixel file sits in `data_kydney.csv`. I am going to adapt the READ.ME

@kelu124 I am going to document more clearly the constants

**Comment by kelu124** [comment]
BTW, where can we find the angles / starting depth for the scan conversion (ideally all the params listed in http://echopen.org/index.php?title=Scan_Conversion )

**Comment by benchoufi** [comment]
hi @kelu124 check out #6. Fixed in 585c0c7 but sure can be improved/detailed. Don't hesitate to write some doc around the class definition if you think it is needed
