### ISSUE TITLE
documentation of scan conversion params 

### ISSUE THREAD

**Issue by benchoufi** [echopen/PRJ-medtec_androidapp#6]
scan conversion params needs to be documented in dimension 

Example : 

 /\* sampling frequency in Hz */
        public static final int SAMPLING_FREQUENCY = (int) Math.pow(100,5);

@loic-fejoz @kelu124

**Comment by kelu124** [comment]
I meant with the angles, starting depth and so on - all linked to the each specific set of raw data - if I want to test on Matlab :)

**Comment by benchoufi** [comment]
if you check the `Constants.java` file, you'll find the data hard coded in `PreProcParam`. For example `start depth` correponds to `RADIAL_IMG_INIT`. Tell me if it is not complete

Fyi, all the constants that depends on the device itself will be set in `Config` class via the `initDisplayInfo` method. You'll find an example of this in 697b08e
