### ISSUE TITLE
Interesting article

### ISSUE THREAD

**Issue by kelu124** [echopen/PRJ-medtec_androidapp#7]
Have you seen that ?
http://publica.fraunhofer.de/starweb/servlet.starweb?path=epub0.web&search=N-360140

**Comment by benchoufi** [comment]
yes, I read a lot of thing about benchmarks betwen CPU/GPU. And for sure, the GPU processing is inevitable. That's a core challenge for the upcoming hackathon we should organize in december ! 
Once a day I should document it on the wiki ;)
